# defaults:
#   - override hydra/launcher: joblib
hydra:
  # launcher:
  #   n_jobs: 12
  job:
    chdir: True
  mode: MULTIRUN
  sweeper:
    params:
      alpha: 0.08,0.10,0.12
      eps: 0.08,0.10,0.12
alpha: 0.05
eps: 0.05
nval: 10
Nval: 2000
sepcontext: True
maxouteriter: 30
