# defaults:
#   - override hydra/launcher: joblib
hydra:
  sweep:
    dir: multirun/lcx_2000_10_1
    subdir: ${hydra.job.num}
  job:
    chdir: True
  mode: MULTIRUN
  sweeper:
    params:
      alpha: 0.10
      eps: 0.10
alpha: 0.05
eps: 0.05
nval: 10
Nval: 2000
sepcontext: True
maxouteriter: 60
numBoots: 10000
