# defaults:
#   - override hydra/launcher: joblib
hydra:
  # launcher:
  #   n_jobs: 12
  job:
    chdir: True
  mode: MULTIRUN
  sweeper:
    params:
      eta: 0.01,0.05,0.10,0.12,0.15,0.20,0.30
      obj_scale: 0.5,1,2
eta: 0.01
obj_scale: 1
seed: 0
lr: 0.0005
num_iter: 501
optimizer: "Adam"
init_rho: 2
init_lam: 2
init_mu: 2
mu_multiplier: 1.02
test_percentage: 0.5
save_history: False
lr_step_size: 20
lr_gamma: 0.5
random_init: False
parallel: False
kappa: 0
contextual: True
max_iter_line_search: 50
line_search: True
max_batch_size: 30
batch_percentage: 0.2
validate_percentage: 0.2
test_frequency: 5000
validate_frequency: 2000
initialize_predictor: True
serial: False
n_val: 10
m_val: 4
sigmult: 0.3
epsrange: 1450
pretrain: True
initseedval: 0
Nval: 1000
epslimtrain: 1450
addval: 0.0
Rvals: 5
knnvals: 30
use_eval: True
knn_mult: 0.95
deep: False
target_eta: 0.1