# defaults:
#   - override hydra/launcher: joblib
hydra:
  sweep:
    dir: results/inv_dro_sep/0
  job:
    chdir: False
  mode: MULTIRUN
  sweeper:
    params:
      idx: 0,1,2,3,4,5,6,7,8,9
idx: 0
seed: 0
test_percentage: 0.5
validate_percentage: 0.2
n_val: 10
m_val: 4
initseedval: 0
Nval: 1000
Rvals: 10
