# defaults:
#   - override hydra/launcher: joblib
hydra:
  sweep:
    dir: results/inv_dro
    subdir: ${hydra.job.num}
  job:
    chdir: True
  mode: MULTIRUN
  sweeper:
    params:
      eta: 0.10
eta: 0.01
seed: 0
test_percentage: 0.5
validate_percentage: 0.2
n_val: 10
m_val: 4
initseedval: 0
Nval: 1000
Rvals: 10
mroK: 30
