# defaults:
#   - override hydra/launcher: joblib
hydra:
  sweep:
    dir: results/inv/dro_sep
  job:
    chdir: True
  mode: MULTIRUN
  sweeper:
    params:
      idx: 0
idx: 0
seed: 0
test_percentage: 0.5
validate_percentage: 0.2
n_val: 10
m_val: 4
initseedval: 0
Nval: 1000
Rvals: 10
