# defaults:
#   - override hydra/launcher: joblib
hydra:
  sweep:
    dir: results/port/dro/30_2000
    subdir: ${hydra.job.num}
  job:
    chdir: True
  mode: MULTIRUN
  sweeper:
    params:
      eta: 0.15
eta: 0.01
seed: 0
test_percentage: 0.5
validate_percentage: 0.2
nval: 30
Rval: 10
Nvals: 2000
Kval: 1
