# defaults:
#   - override hydra/launcher: joblib
hydra:
  sweep:
    dir: results/inv_new/8_500_sep1
    subdir: ${hydra.job.num}
  job:
    chdir: True
  mode: MULTIRUN
  sweeper:
    params:
      eta: 0.05,0.15
      obj_scale: 0.5,2
eta: 0.01
obj_scale: 0.5
seed: 0
lr: 0.001
num_iter: 301
optimizer: "Adam"
init_rho: 3
init_lam: 2
init_mu: 2
mu_multiplier: 1.005
test_percentage: 0.5
save_history: False
lr_step_size: 20
lr_gamma: 0.5
random_init: False
parallel: False
kappa: -0.01
contextual: True
max_iter_line_search: 50
line_search: True
max_batch_size: 30
batch_percentage: 0.2
validate_percentage: 0.2
test_frequency: 5000
validate_frequency: 2000
initialize_predictor: True
serial: False
T_val: 5
initseedval: 0
Nval: 500
knnvals: 30
knn_mult: 0.95
target_eta: 0.1
