# defaults:
#   - override hydra/launcher: joblib
hydra:
  # launcher:
  #   n_jobs: 12
  job:
    chdir: True
  mode: MULTIRUN
  sweeper:
    params:
      eta: 0.01,0.05,0.10,0.12,0.15,0.20,0.25,0.30
      obj_scale: 1,3,5,7,10
      # 1,5,10
      # 12,13,14,15,16
      # 6,7,8,9,10,11
      #0,1,2,3,4,5
eta: 0.01
obj_scale: 1
seed: 0
lr: 0.0001
num_iter: 300
optimizer: "SGD"
init_rho: 1.5
init_lam: 1
init_mu: 1
mu_multiplier: 1.001
test_percentage: 0.5
save_history: True
lr_step_size: 50 #
lr_gamma: 0.5
random_init: False
parallel: False
kappa: 0
contextual: True
max_iter_line_search: 100
line_search: True
max_batch_size: 200
batch_percentage: 0.8
validate_percentage: 0.2
test_frequency: 600
validate_frequency: 100
initialize_predictor: True
knn_mult: 0.95
target_eta: 0.1
Rval: 10
