# defaults:
#   - override hydra/launcher: joblib
hydra:
  sweep:
    dir: results/port/delage/10_2000
    subdir: ${hydra.job.num}
  job:
    chdir: True
  mode: MULTIRUN
  sweeper:
    params:
      eta: 0.05,0.1,0.12,0.15,0.2,0.3
      gam_scale: 0.9,0.6,0.5,0.4,0.2,0.1
eta: 0.05
gam_scale: 0.9
obj_scale: 1
seed: 0
lr: 0.01
num_iter: 300
optimizer: "Adam"
init_rho: 1
init_lam: 1
init_mu: 1
mu_multiplier: 1.005
test_percentage: 0.5
save_history: False
lr_step_size: 50
lr_gamma: 0.9
random_init: False
parallel: False
kappa: 0
contextual: True
max_iter_line_search: 100
line_search: False
max_batch_size: 200
batch_percentage: 0.8
validate_percentage: 0.2
test_frequency: 5000
validate_frequency: 2000
initialize_predictor: True
N_val: 2000
n_val: 10
Rval: 10
seedvals: 0
target_eta: 0.1
