# defaults:
#   - override hydra/launcher: joblib
hydra:
  sweep:
    dir: results/port/dro_sep/30_2000
    subdir: ${hydra.job.num}
  job:
    chdir: True
  mode: MULTIRUN
  sweeper:
    params:
      eta: 0.1
eta: 0.1
seed: 0
test_percentage: 0.5
validate_percentage: 0.2
Rval: 10
n_val: 30
N_val: 2000
